// <auto-generated />
using DiscoGroupie.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiscoGroupie.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DiscoGroupieNpsqlDbContext))]
    partial class DiscoGroupieNpsqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiscoGroupie.Core.Domain.Entities.Guild", b =>
                {
                    b.Property<decimal>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("GroupNamePrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GroupTextSectionId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("GroupVoiceSectionId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds");
                });
#pragma warning restore 612, 618
        }
    }
}
